controller_list:
  - name: fake_crisp_1_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
  - name: fake_crisp_2_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
  - name: fake_crisp_3_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
  - name: fake_crisp_4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_1n2_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
  - name: fake_crisp_1n3_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
  - name: fake_crisp_1n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_2n3_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
  - name: fake_crisp_2n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_3n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_1n2n3_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
  - name: fake_crisp_1n2n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_1n3n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_2n3n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
  - name: fake_crisp_1n2n3n4_controller
    type: $(arg fake_execution_type)
    joints:
      - crisp_1_j1
      - crisp_1_j2
      - crisp_1_j3
      - crisp_1_j4
      - crisp_1_j5
      - crisp_1_j6
      - crisp_2_j1
      - crisp_2_j2
      - crisp_2_j3
      - crisp_2_j4
      - crisp_2_j5
      - crisp_2_j6
      - crisp_3_j1
      - crisp_3_j2
      - crisp_3_j3
      - crisp_3_j4
      - crisp_3_j5
      - crisp_3_j6
      - crisp_4_j1
      - crisp_4_j2
      - crisp_4_j3
      - crisp_4_j4
      - crisp_4_j5
      - crisp_4_j6
initial:  # Define initial robot poses per group
  - group: crisp_1
    pose: arm1_zero
  - group: crisp_2
    pose: arm2_zero
  - group: crisp_3
    pose: arm3_zero
  - group: crisp_4
    pose: arm4_zero
  - group: crisp_1n2n3n4
    pose: arm_all_zero