crisp_1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
  gains:
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
  gains:
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_2n3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
  gains:
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_2n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_3n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n2n3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n2n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n3n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_2n3n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
crisp_1n2n3n4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - crisp_1_j1
    - crisp_1_j2
    - crisp_1_j3
    - crisp_1_j4
    - crisp_1_j5
    - crisp_1_j6
    - crisp_2_j1
    - crisp_2_j2
    - crisp_2_j3
    - crisp_2_j4
    - crisp_2_j5
    - crisp_2_j6
    - crisp_3_j1
    - crisp_3_j2
    - crisp_3_j3
    - crisp_3_j4
    - crisp_3_j5
    - crisp_3_j6
    - crisp_4_j1
    - crisp_4_j2
    - crisp_4_j3
    - crisp_4_j4
    - crisp_4_j5
    - crisp_4_j6
  gains:
    crisp_1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_3_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    crisp_4_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1